### PR TITLE
Ft edit incidents comment

### PR DESCRIPTION
**Pull request by llwasampijja**
Can edit incidents' comment and location.

Login as Jane
username: jane
password: passworD#1

Reviews and feedback are highly welcome.
Thanks, Jah bless, Selah!

@nicholus @Rhytah @JamesMudidi @sanya-kenneth @frankopkusianwar @ManuelDominic @KabohaJeanMark @nadralia @reifred @llwasampijja @richien @Genza999 @3Nakajugo @e-ian @Manorlds-Eaglespark @PatrickMugayaJoel @bisonlou @v1b3m @mwinel @sebbss

### CODE REVIEW

**Comment by Rhytah** [comment]
- Could you please indicate url we can use to access application and features.

- I can suggest change of image on signup page, it seems to convey a different context from project description.

- After successful signup. The dashboard is in a state of constant uninterruptible reload and switching between `login.html`  and `my_reports.html` pages. I couldn't do much on app at this point. Consider fixing this. Problem could be in your javascript.

**Comment by llwasampijja** [comment]
> * Could you please indicate url we can use to access application and features.
> * I can suggest change of image on signup page, it seems to convey a different context from project description.
> * After successful signup. The dashboard is in a state of constant uninterruptible reload and switching between `login.html`  and `my_reports.html` pages. I couldn't do much on app at this point. Consider fixing this. Problem could be in your javascript.

thanks @Rhytah , let me look into that issue

**Comment by ghost** [comment]
@llwasampijja. I have looked through your pull request plus the UI fetch implementation but:-
- When I signed up, I was logged in as an admin because I see the *admin panel*.
- I was unable to create an incident in order to test for the edit too.
However, I suggest not to make it difficult for the user forcefully to have such a complicated password. with symbols then the upper case, however, Ensure the length and at least one difference of uppercase if your reason is for security.

**Comment by llwasampijja** [comment]
> @llwasampijja. I have looked through you pull request plus the UI fetch implementation but:-
> 
> * When I signed up, I was logged in as an admin because I see the _admin panel_.
> * I was unable to create an incident in order to test for the edit too.
>   However, I suggest not to make it difficult for the user forcefully to have such a complicated password. with symbols then the upper case, however, Ensure the length and at least one difference of uppercase if your reason is for security. It is safe to say that is the current password security standard

thanks @ManuelDominic, You were logged in as a normal user, I am going to correct that heading, it isn't supposed to be Admin Panel. As for creating an incident, I am yet to implement that feature. To test editing, try logging in as Jane: username: jane password: passworD#1

As for the password, I think I am going to leave it at that. I recently signed up with URA and their password specification is exactly similar to this.

**Comment by v1b3m** [comment]
Hey is it possible that you add a url to your UI here, sir.
tenk yuh

**Pull request merged**
