### PR TITLE
Pull request number 3.

### PR DESCRIPTION
**Pull request by llwasampijja**
Hello comrades,
I ask you to spare some time and review my current code and offer some advice before I merge it into the develop branch. Thanks.

@WalujoEmmanuel @ringtho @KapsonLabs @MukuruH @bakersen @Kyeza @nadralia @Kwandera @JammyKalungi @reifred @ernesthenry @jennizalwango @jkMugabe @richien @Araali1 @Mastula77 @Genza999 @Wabuluka @vicentbaiga @noahkalyesubula @LynetteMK @joekirumira @bashirdeveloper @lizz24 @kalsmic @erioc @mwes23 @NANKYAPHIONA @HarunaIbnYusuf @k7ko @v1b3m @KengoWada @codephillip @SimiCode  @kdenno, @candysusan @bekeplar @masete

### CODE REVIEW

**Comment by kalsmic** [comment]
When I click on the link to the swagger documentation, it shows a privacy error "NET:: ERR_CERT_COMMON_NAME_INVALID"  and when I add the rule to my browser, I am redirected to a page on Heroku that says, "There's nothing here, yet. "

**Comment by kalsmic** [comment]
The documentation for postman works well though. KUDOS

**Comment by bekeplar** [comment]
Your work is good. I have emulated some concepts. But work on your documentation

**Comment by reifred** [comment]
NET::ERR_CERT_COMMON_NAME_INVALID on swagger documentation link.

**Comment by llwasampijja** [comment]
> NET::ERR_CERT_COMMON_NAME_INVALID on swagger documentation link.

@reifred the feature-temp branch is the one with the correct link, the one which i made the pull request for

**Comment by llwasampijja** [comment]
> Your work is good. I have emulated some concepts. But work on your documentation

@bekeplar thanks a lot, Jah Bless. About the documentation, what should I work on? shed some light on that, please! And what documentation are you referring to, the readme, Postman or Swagger-UI? The working links to these are under the feature-temp branch

**Pull request closed without merging**
