### PR TITLE
Pull request: No1

### PR DESCRIPTION
**Pull request by llwasampijja**
Please, review my API endpoints code. Thank you! 

@WalujoEmmanue @ringtho @KapsonLabs @MukuruH @bakersen @Kyeza @nadralia @Kwandera @JammyKalungi @reifred @ernesthenry @jennizalwango @jkMugabe @richien @araali1 @Mastula77 @Genza999 @Wabuluka @vicentbaiga @noahkalyesubula @LynetteMK @joekirumira @bashirdeveloper @lizz24 @kalsmic @erioc @mwes23 @NANKYAPHIONA @HarunaIbnYusuf @k7ko @v1b3m @KengoWada

### CODE REVIEW

**Comment by jkMugabe** [comment]
Good, it's nice

**Comment by v1b3m** [comment]
Looks great,
maybe consider changing *if len(get_redflags_instance) <= 0:* with *if not get_redflags_instance*

**Comment by llwasampijja** [comment]
> Looks great,
> maybe consider changing _if len(get_redflags_instance) <= 0:_ with _if not get_redflags_instance_

Thanks a lot, I have implemented it, its way shorter and cleaner than the one I had used! thanks!

**Comment by Mastula77** [comment]
I think its working out

**Comment by llwasampijja** [comment]
> I think its working out

Thanks, I appreciate

**Comment by jennizalwango** [comment]
ohh l have just checked your work but its nice l like the way you write
your README

**Comment by llwasampijja** [comment]
@jennizalwango thanks!

**Pull request closed without merging**
