### PR TITLE
Can update incident status endpoint using UI

### PR DESCRIPTION
**Pull request by llwasampijja**
Hi people, 
Take some time to test and review my work,
login as admin: username: edward, password: i@mG8t##

link to feature:
https://llwasampijja.github.io/ireporter-challenge-two/UI/admin_panel.html
Thanks, Jah Bless, Selah!

### CODE REVIEW

**Comment by kalsmic** [comment]
@llwasampijja, The feature works as expected. :+1:

**Comment by fodongkara** [comment]
It appears the page is not protected. It should redirect me to login if I have no session.

**Comment by kalsmic** [comment]
Ooops, @llwasampijja I did not test for this

> It appears the page is not protected. It should redirect me to login if I have no session.

**Comment by llwasampijja** [comment]
> It appears the page is not protected. It should redirect me to login if I have no session.

Let me continue sorting out the kinks on this feature

**Comment by llwasampijja** [comment]
@kalsmic and @fodongkara You can try out the pages that I have protected using javascript and offer me your recommendations!
bless!

**Pull request closed without merging**
