### PR TITLE
Added endpoint for editing comment of a redflag [Delivers #163350001]

### PR DESCRIPTION
**Pull request by llwasampijja**
Hello
I welcome and appreciate reviews and feedback for my code.
Thank you.

### CODE REVIEW

**Comment by jennizalwango** [comment]
Nice code man!

**Comment by jennizalwango** [comment]
The readMe is so descriptive which is good

**Comment by llwasampijja** [comment]
> I feel like you have done a good job with your code however the lack of comments is making it hard for me to understand it faster. Please consider including comments for your code. Thanks

Ok, let me do that @Wabuluka thanks man!

**Comment by llwasampijja** [comment]
> The readMe is so descriptive which is good

Thanks @jennizalwango

**Pull request merged**
